### ISSUE TITLE
Warning: don't setup your environment using anaconda.

### ISSUE THREAD

**Issue by dragon9001** [mitmul/ssai-cnn#18]
This project use Chianer as its deep learning framework. 
However, Chianer is based on a Cuda driver named CUPY, which is(seemingly) not supported by any Anaconda library.
Therefore setup environment using anaconda will always result in fail to find cupy module.

I tried to using system python cupy library and conda chainer library with no luck.
If any one has solution, please follow this issue.

**Comment by Tejuwi** [comment]
It works for me. I have used cuda 8.0 and anconda 3.5.

**Comment by mitmul** [comment]
@dragon9001 This repo is using Chainer 1.5.0.2. If you are talking about the separate package named "CuPy", you may be using a wrong version of Chainer. Chainer 1.5 does not need CuPy as a separate package so you don't need to install CuPy to use GPU with Chainer. After 1.6, you need to install CuPy, though. Could you try to use the right version of Chainer written in the README of this repo?

**Comment by dragon9001** [comment]
Thanks, for the information about that 1.6 relys on Cupy while 1.5 doesn't. I finally had it worked. Thanks again!
