### ISSUE TITLE
import Error

### ISSUE THREAD

**Issue by mshakaib** [mitmul/ssai-cnn#24]
I am using python 3.6 on win 10
I run the script create_dataset
Found this Error
ModuleNotFoundError: No module named 'utils.patches'
the Error relates to this lines:
from utils.patches import divide_to_patches

 Kindly help..

**Comment by Kkevin4** [comment]
Have you solved the problem?

**Comment by 874431052** [comment]
> I am using python 3.6 on win 10
> I run the script create_dataset
> Found this Error
> ModuleNotFoundError: No module named 'utils.patches'
> the Error relates to this lines:
> from utils.patches import divide_to_patches
> 
> Kindly help..

I have the same problem, what should I do??
